"""baseline schema (all tables from metadata)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-19

Baseline migration: creates the full schema from the SQLAlchemy metadata. From
here on, schema changes must be added as proper autogenerated migrations
(`alembic revision --autogenerate -m "..."`).
"""
from __future__ import annotations

from alembic import op

import app.models  # noqa: F401 — register all models on metadata
from app.db.base import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind)
